### ISSUE TITLE
Compatibility with old NI cards (PCI-6024E)

### ISSUE THREAD

**Issue by matteo-pizzotti** [RTXI/rtxi#172]
Hi,

I've just installed the latest RTXI version (3.0.3 + evl kernel) on a fresh Ubuntu 22.04.4.
I have an old NI DAQ card, PCI-6024E, which is not supported in Ubuntu by NI native drivers (last ni-daq mx compatible version is 19.5, that is only available for CentOS). With older versions of RTXI I was able to communicate with the card through analogy driver, that is not supported anymore in this latest RTXI version, if I understand correclty.

Which options do I have?
If i try to install RTXI 3.0.3 on a Centos OS, with the proper NI drivers installed, will I be able to use the PCI-6024E card?
Alternatively, which is the last RTXI version supporting analogy drivers?
Is there something else that I'm missing?

Thank you for your support

Matteo

**Comment by fusge** [comment]
﻿
Hi Matteo,

Unfortunately RTXI does not support this card because it dropped support for analogy devices. Xenomai 4 dropped support for analogy drivers and Xenomai 3 does not actively support the analogy framework.

What this all means is that RTXI 3.0 onwards will not support analogy based devices and will instead rely on NI library interface for DAQ control. This leaves you with two choices:

1) upgrade to a newer PCI DAQ card that is supported by the nidaqmx library(recommended)

2) downgrade OS kernel to support your device

I would recommend option one. Trying to install on centos with NI drivers should work in theory but we don't have any tests to confirm whether it would work. There is also the issue of getting the dependencies to install on the older kernel, as well as installing the real-time kernel.

Ivan F. Valerio

**Comment by matteo-pizzotti** [comment]
Dear Ivan,

thank you for your reply.
Sorry for this late response, we've been discussing about how to proceed. We've decided to buy a new card, so I have another doubt. I read from your "Getting started" that:

"The Xenomai project may still support PCI cards, but not PCIe, and we do not test them so we cannot give you a recommendation to use them. Instead we advice downloading and installing the NIDAQmx library, which supports a wide range of National Instruments DAQ cards and is the interface used by RTXI"

Does it mean, for example, that a PCIe-6321 will not work with RXI despite is supported by the NIDAQmx library? In other words, do I have necessarily switch to a PXIe interface?

Thanks again for your support

Matteo

**Comment by fusge** [comment]
> "The Xenomai project may still support PCI cards, but not PCIe, and we do not test them so we cannot give you a recommendation to use them. Instead we advice downloading and installing the NIDAQmx library, which supports a wide range of National Instruments DAQ cards and is the interface used by RTXI"

This refers to Analogy drivers which are part of the Xenomai 3.x versions. These DAQ drivers are no longer maintained by Xenomai and support will be dropped in future iterations of the kernel. For new installations you should install the NIDAQ drivers instead.

PCIe-6321 is a fine card and we've used it as well with the latest RTXI version. If you install NIDAQ drivers before installing RTXI then it should be automatically configured for you on program startup.

**Comment by matteo-pizzotti** [comment]
Thank you very much for your support

**Comment by fusge** [comment]
I will be closing this issue. If there are any other questions or problems feel free to open a new ticket.
